name: port
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.3
  lottie: ^3.3.1
  icons_plus: ^5.0.0
  flutter_staggered_animations: ^1.1.1
  video_player: ^2.9.5
  chewie: ^1.11.3
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  color: "#000000"
  web: true
  image: assets/images/logo.png
  image_dark: assets/images/logo.png
  color_dark: "#000000"

flutter_launcher_icons:
  android: true
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#000000"
    theme_color: "#000000"
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1


flutter:

  uses-material-design: true

  assets:
    - assets/animation/port.json
    - assets/images/splash.png